name: CI for go Code # Naming the workflow
on: #for event triggering
  push:
    branches: [main] #add with comma for more branches to monitor
  pull_request:
    branches: [main] #for multiple branches(main is also a branch), [main, xxxfile]
    
jobs: #job to execute?
  build: #name of the job
    name: Load OS #name for printing
    runs-on: ubuntu-latest #specify OS in virtual machine of github
    steps: 
    - name: Print hello
      run: | #run terminal command - pipe to run the various commends sequentially
        ls
        echo Hello!!
        
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        
    - name: Setup Go ##action of setup go
      uses: actions/setup-go@v3.2.0 #running go 
      with: 
        go-version: 1.18 #with version 1.18
        
    - name: Check Go Version
      run: go version 
      
    - name: Checkout Repo #this checks out a git repo in the go 
      uses: actions/checkout@v2.4.2
      
      #private repository here
#     - name: Checkout Remote Private Repo
#       uses: actions/checkout@v2.4.2
#       with:
#         repository: lowkh2/GoSchoolRemoteExample #goes to a private repository url
#         token: ${{  secrets.GO_SECRET }}   #uses the token
#         path: remote #remote folder
#     - name: Check remote files
#       run: | #ls to see whats the 
#         cd remote
#         ls 
#         cat myText.txt #print out content of the text file
#         cd ..
        
        
      
    - name: Check File System
      run: ls
      
    - name: Install dependencies
      run: |
        go get github.com/franela/goblin
        go install github.com/tebeka/go2xunit@latest
        go test -v
        go test -v | go2xunit > tests.xml
        
    - name: Publish Test Results #https://github.com/EnricoMi/publish-unit-test-result-action
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:  #for windows user, need "test-results/**/*.xml"
        files: tests.xml #"test-results/**/*.xml"
        
     #https://github.com/nashmaniac/create-issue-action   
    - if: ${{failure()}} #space between keywords and after, no difference; ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
        
  
