name: CI for go Code # Naming the workflow
on: #for event triggering
  push:
    branches: [main] #add with comma for more branches to monitor
  pull_request:
    branches: [main] #for multiple branches(main is also a branch), [main, xxxfile]
    
jobs: #job to execute?
  build: #name of the job
    name: Load OS #name for printing
    runs-on: ubuntu-latest #specify OS in virtual machine of github
    steps: 
    - name: Print hello
      run: | #run terminal command - pipe to run the various commends sequentially
        ls
        echo Hello!!
    - name: Setup Go ##action of setup go
      uses: actions/setup-go@v3.2.0 #running go 
      with: 
        go-version: 1.18 #with version 1.18
    - name: Check Go Version
      run: go version 
      
    - name: Checkout Repo #this checks out a git repo in the go 
      uses: actions/checkout@v2.4.2
      
    - name: Check File System
      run: ls
